wmdadict/urls.py
from django.conf.urls import url

from . import views

app_name = 'wmdadict'
urlpatterns = [
    # # /
    # url(r'^$', views.index, name='index'),
    # /dict/
    url(r'^dict/$', views.dictionary_list, name='dictionary_list'),
    # /dict/5/
    url(r'^dict/(?P<field_id>[0-9]+)/$', views.dictionary_detail, name='dictionary_detail'),
    # /emdis/fields/
    url(r'^emdis/fields/$', views.emdis_list, name='emdis_list'),
    # /emdis/field/5/
    url(r'^emdis/field/(?P<field_id>[0-9]+)/$', views.emdis_detail, name='emdis_detail'),
    # /emdis/messages/
    url(r'^emdis/messages/$', views.emdis_msg_list, name='emdis_msg_list'),
    # /emdis/message/5/
    url(r'^emdis/message/(?P<msg_id>[0-9]+)/$', views.emdis_msg_detail, name='emdis_msg_detail'),
    # /bmdw/
    url(r'^bmdw/$', views.bmdw_list, name='bmdw_list'),
    # /bmdw/5/
    url(r'^bmdw/(?P<field_id>[0-9]+)/$', views.bmdw_detail, name='bmdw_detail'),
    # /form/
    url(r'^form/$', views.form_list, name='form_list'),
    # /form/5/
    url(r'^form/(?P<field_id>[0-9]+)/$', views.form_detail, name='form_detail'),
]

wmdasite/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView

from wmdadict.admin import wmda_admin_site


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'', include('wmdadict.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^admin/', wmda_admin_site.urls),
]

if settings.LOCAL_DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

wmdadict/models.py
from django.db import models

from ordered_model.models import OrderedModel
# from markdownx.models import MarkdownxField

#
# Helper models
#

class DataFamily(models.Model):
    name = models.CharField(max_length=50, unique=True)
    contact = models.CharField(max_length=50, blank=True,
            help_text="Formatting and newlines will not be displayed.")

    class Meta:
        verbose_name_plural = 'data families'

    def __str__(self):
        return self.name


class DictionaryFieldType(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    has_units = models.BooleanField()
    has_range = models.BooleanField()
    has_values = models.BooleanField()

    class Meta:
        ordering = ['title',]

    def __str__(self):
        return self.title


class EmdisFieldType(models.Model):
    letter_code = models.CharField(max_length=1, unique=True)
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True,
        help_text="Formatting and newlines will not be displayed.")

    class Meta:
        verbose_name = 'EMDIS field type'
        ordering = ['letter_code',]

    def __str__(self):
        return self.title


class RequiredFieldType(models.Model):
    emdis_label = models.CharField(max_length=30)
    bmdw_label = models.CharField(max_length=30)
    description = models.TextField(blank=True)
    display_strong = models.BooleanField()

    def __str__(self):
        return '/'.join([self.emdis_label, self.bmdw_label,])


class BmdwElementType(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True,
        help_text="Formatting and newlines will not be displayed.")

    class Meta:
        verbose_name = 'BMDW element type'
        ordering = ['title',]

    def __str__(self):
        return self.title


class BmdwFieldType(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True,
        help_text="Formatting and newlines will not be displayed.")

    class Meta:
        verbose_name = 'BMDW field type'
        ordering = ['title',]

    def __str__(self):
        return self.title


#
# Primary Data Dictionary models
#

class DictionaryField(models.Model):
    label = models.CharField(max_length=200, unique=True)
    description_short = models.CharField('Short Description', max_length=200)
    description_long = models.TextField('Long Description', blank=True)
    field_type = models.ForeignKey(DictionaryFieldType,
                                   on_delete=models.PROTECT,)
    units = models.CharField(max_length=200, blank=True)
    range = models.CharField(max_length=200, blank=True)
    values = models.TextField(max_length=1000, blank=True)
    owner_family = models.ForeignKey(DataFamily,
                                     on_delete=models.PROTECT,
                                     related_name='owns',)
    user_families = models.ManyToManyField(DataFamily,
                                           blank=True,
                                           related_name='uses',)

    class Meta:
        ordering = ['label']

    def __str__(self):
        return self.label


class EmdisMessage(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=200)
    pre_text = models.TextField(max_length=10000, blank=True)
    post_text = models.TextField(max_length=10000, blank=True)

    class Meta:
        verbose_name = 'EMDIS message'
        ordering = ['name']

    # @property
    # def sorted_field_set(self):
    #     return self.emdisfield_set.order_by('emdissemantics__order')

    def __str__(self):
        return self.name


class EmdisField(models.Model):
    field_code = models.CharField(max_length=50, unique=True)
    field_description = models.CharField(max_length=500)
    emdis_type = models.ForeignKey(EmdisFieldType,
                                   on_delete=models.PROTECT,
                                   verbose_name='field type',)
    field_length = models.PositiveIntegerField()
    field_rule = models.TextField()
    dict_field = models.ForeignKey(DictionaryField,
                                   on_delete=models.PROTECT,
                                   verbose_name='WMDA Dictionary Field')
    emdis_messages = models.ManyToManyField(EmdisMessage,
                                            through='EmdisSemantics')

    class Meta:
        verbose_name = 'EMDIS field'
        ordering = ['field_code']

    def __str__(self):
        return self.field_code


class EmdisSemantics(OrderedModel):
    emdis_field = models.ForeignKey(EmdisField,
                                    on_delete=models.PROTECT,)
    emdis_message = models.ForeignKey(EmdisMessage,
                                      on_delete=models.PROTECT,)
    required = models.ForeignKey(RequiredFieldType,
                                 on_delete=models.PROTECT,)

    order_with_respect_to = 'emdis_message'

    class Meta(OrderedModel.Meta):
        ordering = ('emdis_message', 'order')


class BmdwField(models.Model):
    field_identifier = models.CharField(max_length=50)
    element_type = models.ForeignKey(BmdwElementType,
                                         on_delete=models.PROTECT,)
    required = models.ForeignKey(RequiredFieldType,
                                 on_delete=models.PROTECT,)
    description = models.TextField(blank=True)
    type = models.ForeignKey(BmdwFieldType,
                             on_delete=models.PROTECT,)
    length = models.CharField(max_length=50, blank=True)
    comment = models.TextField(blank=True)
    dict_field = models.ForeignKey(DictionaryField,
                                   verbose_name='WMDA Dictionary Field',
                                   on_delete=models.PROTECT,)

    class Meta:
        verbose_name = 'BMDW field'
        ordering = ('element_type', 'field_identifier',)

    def __str__(self):
        return self.field_identifier


class WmdaForm(models.Model):
    form_code = models.CharField(max_length=10, unique=True)
    description = models.CharField(max_length=200, blank=True)
    form_url = models.URLField(max_length=200, blank=True)
    fields = models.ManyToManyField(DictionaryField,
                                    through='FormFields')

    class Meta:
        verbose_name = 'WMDA form'

    def __str__(self):
        return self.form_code


class FormFields(OrderedModel):
    dict_field = models.ForeignKey(DictionaryField,
                                   on_delete=models.PROTECT,
                                   verbose_name='WMDA Dictionary Field')
    wmda_form = models.ForeignKey(WmdaForm,
                                  on_delete=models.PROTECT,)
    form_field_name = models.CharField(max_length=200)
    form_field_current_name = models.CharField(max_length=200, blank=True)
    order_with_respect_to = 'wmda_form'

    class Meta:
        verbose_name_plural = 'form fields'
        ordering = ('wmda_form', 'order')

wmdadict/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from markdownx.utils import markdownify

from .models import DictionaryField, EmdisField, EmdisMessage
from .models import BmdwField, WmdaForm
from .filters import DictionaryFilter, EmdisFieldFilter, EmdisMessageFilter
from .filters import BmdwFieldFilter, WmdaFormFilter

# def index(request):
#     return HttpResponse("Hello, world. You're at the WMDA Dictionary index.")

def dictionary_list(request):
    dictionaryfields = DictionaryField.objects.all()
    field_filter = DictionaryFilter(request.GET, queryset=dictionaryfields)
    if any(v != '' for v in request.GET.dict().values()):
        filter_active = True
    else:
        filter_active = False
    filter_context = {'filter_active': filter_active}
    return render(request, 'wmdadict/dictionary_list.html',
                                {'dict_fields': field_filter,
                                 'filter_context': filter_context})

def dictionary_detail(request, field_id):
    dictionaryfield = get_object_or_404(DictionaryField, pk=field_id)
    dictionaryfield.description_long = markdownify(dictionaryfield.description_long)
    if dictionaryfield.values:
        dictionaryfield.values = markdownify(dictionaryfield.values)
    forms = dictionaryfield.formfields_set.all().distinct('wmda_form')
    return render(request,
                  'wmdadict/dictionary_detail.html',
                  {'dfield': dictionaryfield,
                   'forms': forms})

def emdis_list(request):
    emdis_fields = EmdisField.objects.all()
    field_filter = EmdisFieldFilter(request.GET, queryset=emdis_fields)
    if any(v != '' for v in request.GET.dict().values()):
        filter_active = True
    else:
        filter_active = False
    filter_context = {'filter_active': filter_active}

    return render(request,
                  'wmdadict/emdis_list.html',
                  {'emdis_fields': field_filter,
                  'filter_context': filter_context})

def emdis_detail(request, field_id):
    emdisfield = get_object_or_404(EmdisField, pk=field_id)
    emdisfield.field_rule = markdownify(emdisfield.field_rule)
    return render(request, 'wmdadict/emdis_detail.html', {'efield': emdisfield})

def emdis_msg_list(request):
    msg_fields = EmdisMessage.objects.all()
    msg_filter = EmdisMessageFilter(request.GET, queryset=msg_fields)
    if any(v != '' for v in request.GET.dict().values()):
        filter_active = True
    else:
        filter_active = False
    filter_context = {'filter_active': filter_active}
    return render(request,
                 'wmdadict/emdis_msg_list.html',
                 {'msg_filter': msg_filter,
                 'filter_context': filter_context})

def emdis_msg_detail(request, msg_id):
    emsg = get_object_or_404(EmdisMessage, pk=msg_id)
    if emsg.pre_text:
        emsg.pre_text = markdownify(emsg.pre_text)
    if emsg.post_text:
            emsg.post_text = markdownify(emsg.post_text)
    return render(request, 'wmdadict/emdis_msg_detail.html', {'emsg': emsg})

def bmdw_list(request):
    bmdwfields = BmdwField.objects.all()
    bmdwfilter = BmdwFieldFilter(request.GET, queryset=bmdwfields)
    if any(v != '' for v in request.GET.dict().values()):
        filter_active = True
    else:
        filter_active = False
    filter_context = {'filter_active': filter_active}
    return render(request,
                  'wmdadict/bmdw_list.html',
                  {'bmdwfilter': bmdwfilter,
                  'filter_context': filter_context})

def bmdw_detail(request, field_id):
    bmdwfield = get_object_or_404(BmdwField, pk=field_id)
    bmdwfield.description = markdownify(bmdwfield.description)
    bmdwfield.comment = markdownify(bmdwfield.comment)
    return render(request, 'wmdadict/bmdw_detail.html', {'bmdwfield': bmdwfield})

def form_list(request):
    wmdaforms = WmdaForm.objects.all()
    formfilter = WmdaFormFilter(request.GET, queryset=wmdaforms)
    if any(v != '' for v in request.GET.dict().values()):
        filter_active = True
    else:
        filter_active = False
    filter_context = {'filter_active': filter_active}
    return render(request,
                  'wmdadict/form_list.html',
                  {'formfilter': formfilter,
                   'filter_context': filter_context})

def form_detail(request, field_id):
    wmdaform = get_object_or_404(WmdaForm, pk=field_id)
    return render(request, 'wmdadict/form_detail.html', {'wmdaform': wmdaform})

wmdadict/templates/wmdadict/dictionary_detail.html
{% extends 'base.html' %}

{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'wmdadict:dictionary_list' %}">WMDA Dictionary</a></li>
    <li class="active">{{ dfield }}</li>
{% endblock %}


{% block content %}
    <h1 class="text-center">WMDA Dictionary field: {{ dfield }}</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped tablesorter">
                <tbody>
                        <tr>
                            <td>Description</td>
                            <td>{{ dfield.description_short }}</td>
                        </tr>
                        <tr>
                            <td>Description (long)</td>
                            <td>{{ dfield.description_long|safe }}</td>
                        </tr>
                        <tr>
                            <td>Field type</td>
                            <td>
                                <span data-toggle="popover"
                                      title="{{ dfield.field_type.title }}"
                                      data-content="{{ dfield.field_type.description }}">
                                          {{ dfield.field_type.title }} <i class="glyphicon glyphicon-info-sign"></i>
                                </span>
                            </td>
                        </tr>
                        {% if dfield.field_type.has_units %}
                            <tr>
                                <td>Units</td>
                                <td>{{ dfield.units }}</td>
                            </tr>
                        {% endif %}
                        {% if dfield.field_type.has_range %}
                            <tr>
                                <td>Range</td>
                                <td>{{ dfield.range }}</td>
                            </tr>
                        {% endif %}
                        {% if dfield.field_type.has_values %}
                            <tr>
                                <td>Values</td>
                                <td>{{ dfield.values|safe }}</td>
                            </tr>
                        {% endif %}
                        <tr>
                            <td>Data family owner</td>
                            <td>
                                <span data-toggle="popover"
                                      title="{{ dfield.owner_family.name }}"
                                      data-content="Contact: {{ dfield.owner_family.contact }}">
                                          {{ dfield.owner_family }} <i class="glyphicon glyphicon-info-sign"></i>
                                </span>
                            </td>
                        </tr>
                        {% if dfield.user_families.all %}
                            <tr>
                                <td>Data family users</td>
                                <td>
                                    {% for family in dfield.user_families.all %}
                                        {{ family.name }}<br />
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endif %}
                        {% if dfield.emdisfield_set.all %}
                            <tr>
                                <td>EMDIS fields</td>
                                <td>
                                    {% for efield in dfield.emdisfield_set.all %}
                                        <a href="{% url 'wmdadict:emdis_detail' efield.pk %}">{{ efield.field_code }}</a><br />
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endif %}
                        {% if dfield.bmdwfield_set.all %}
                            <tr>
                                <td>BMDW fields</td>
                                <td>
                                    {% for bfield in dfield.bmdwfield_set.all %}
                                        <a href="{% url 'wmdadict:bmdw_detail' bfield.pk  %}">{{ bfield.field_identifier }}</a><br />
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endif %}
                        {% if forms %}
                            <tr>
                                <td>Forms</td>
                                <td>{% for ffield in forms %}
                                        <a href="{% url 'wmdadict:form_detail' ffield.wmda_form.pk %}">{{ ffield.wmda_form }} ({{ ffield.wmda_form.description }})</a><br />
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endif %}
                </tbody>
            </table>
        </div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
</script>
{% endblock %}

wmdadict/templates/wmdadict/emdis_detail.html
{% extends 'base.html' %}

{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'wmdadict:emdis_list' %}">EMDIS Fields</a></li>
    <li class="active">{{ efield }}</li>
{% endblock %}


{% block content %}
    <h1 class="text-center">EMDIS field: {{ efield }}</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped tablesorter">
                <tbody>
                        <tr>
                            <td>Field code</td>
                            <td>{{ efield.field_code }}</td>
                        </tr>
                        <tr>
                            <td>Field description</td>
                            <td>{{ efield.field_description }}</td>
                        </tr>
                        <tr>
                            <td>Field type</td>
                            <td>
                                <span data-toggle="popover"
                                      title="{{ efield.emdis_type.title }}"
                                      data-content="{{ efield.emdis_type.description }}">
                                          {{ efield.emdis_type.title }} <i class="glyphicon glyphicon-info-sign"></i> <em>Length: {{ efield.field_length }}</em>
                                </span>
                            </td>
                        </tr>
                        <tr>
                            <td>Field rule</td>
                            <td>{{ efield.field_rule|safe }}</td>
                        </tr>
                        <tr>
                            <td>Dictionary field</td>
                            <td><a href="{% url 'wmdadict:dictionary_detail' efield.dict_field.pk %}">{{ efield.dict_field }}</a> ({{ efield.dict_field.description_short }})
                            </td>
                        </tr>
                        <tr>
                            <td>EMDIS messages</td>
                            <td>
                                {% for message in efield.emdis_messages.all %}
                                    <a href="{% url 'wmdadict:emdis_msg_detail' message.pk %}">{{ message }}</a><br />
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <td>BMDW fields related to dictionary field</td>
                            <td>
                                {% for bfield in efield.dict_field.bmdwfield_set.all %}
                                    <a href="{% url 'wmdadict:bmdw_detail' bfield.pk %}">{{ bfield.field_identifier }}<br />
                                {% endfor %}
                            </td>
                        </tr>
                </tbody>
            </table>
        </div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
</script>
{% endblock %}

wmdadict/templates/wmdadict/emdis_msg_detail.html
{% extends 'base.html' %}

{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'wmdadict:emdis_msg_list' %}">EMDIS Messages</a></li>
    <li class="active">{{ emsg }}</li>
{% endblock %}


{% block content %}
    <h1 class="text-center">EMDIS message: {{ emsg }}</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped tablesorter">
                <tbody>
                        <tr>
                            <td>Name</td>
                            <td>{{ emsg.name }}</td>
                        </tr>
                        <tr>
                            <td>Description</td>
                            <td>{{ emsg.description }}</td>
                        </tr>
                </tbody>
            </table>
        </div>

        {% if emsg.pre_text %}
            <div class="table-responsive">
                <table class="table table-bordered">
                    <tbody>
                            <tr>
                                <td>{{ emsg.pre_text|safe }}</td>
                            </tr>
                    </tbody>
                </table>
            </div>
        {% endif %}

        <h4>EMDIS Fields</h4>
            {% if emsg.emdisfield_set %}
                <div class="table-responsive">
                    <table class="table table-hover table-striped tablesorter">
                        <thead>
                            <tr>
                                <th class="header col-sm-4"> Field description (WMDA dictionary field) <i class="icon-sort"></i></th>
                                <th class="header col-sm-3"> EMDIS field code <i class="icon-sort"></i></th>
                                <th class="header col-sm-2"> Required <i class="icon-sort"></i></th>
                                <th class="header col-sm-3"> Field Type <i class="icon-sort"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in emsg.emdissemantics_set.all %}
                                <tr>
                                    <td>{{ row.emdis_field.field_description }} (<a href="{% url 'wmdadict:dictionary_detail' row.emdis_field.dict_field.pk %}">{{ row.emdis_field.dict_field }})</a></td>
                                    <td><a href="{% url 'wmdadict:emdis_detail' row.emdis_field.pk %}">{{ row.emdis_field }}</a></td>
                                    <td>
                                        {% if row.required.display_strong %}
                                            <strong>{{ row.required.emdis_label }}</strong>
                                        {% else %}
                                            {{ row.required.emdis_label }}
                                        {% endif %}
                                    </td>
                                    <td>
                                        <span data-toggle="popover"
                                              title="{{ row.emdis_field.emdis_type.title }}"
                                              data-content="{{ row.emdis_field.emdis_type.description }}">
                                                {{ row.emdis_field.emdis_type.letter_code }}{{ row.emdis_field.field_length }} <i class="glyphicon glyphicon-info-sign"> </i>
                                        </span>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                {% if emsg.post_text %}
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <tbody>
                                    <tr>
                                        <td>{{ emsg.post_text|safe }}</td>
                                    </tr>
                            </tbody>
                        </table>
                    </div>
                {% endif %}

            {% else %}
                <p>No EMDIS fields are available.</p>
            {% endif %}
{% endblock %}

{% block javascript %}
<script type="text/javascript">
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});
</script>
{% endblock %}

wmdadict/templates/wmdadict/form_detail.html
{% extends 'base.html' %}

{% block breadcrumbs %}
    {{ block.super }}
    <li><a href="{% url 'wmdadict:form_list' %}">WMDA Forms</a></li>
    <li class="active">{{ wmdaform }}</li>
{% endblock %}


{% block content %}
    <h1 class="text-center">WMDA form: {{ wmdaform }}</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped tablesorter">
                <tbody>
                        <tr>
                            <td>Name</td>
                            <td>{{ wmdaform.form_code }}</td>
                        </tr>
                        <tr>
                            <td>Description</td>
                            <td>{{ wmdaform.description }}</td>
                        </tr>
                </tbody>
            </table>
            </div>
            <h4>Dictionary Fields</h4>
            {% if wmdaform.formfields_set %}
                <div class="table-responsive">
                    <table class="table table-hover table-striped tablesorter">
                        <thead>
                            <tr>
                                <th class="header col-sm-3"> Name of field on form <i class="icon-sort"></i></th>
                                <th class="header col-sm-5"> Dictionary label (description) <i class="icon-sort"></i></th>
                                <th class="header col-sm-2"> EMDIS fields (matching dictionary field) <i class="icon-sort"></i></th>
                                <th class="header col-sm-2"> BMDW fields (matching dictionary field) <i class="icon-sort"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in wmdaform.formfields_set.all %}
                                <tr>
                                    <td>{{ row.form_field_name }}</td>
                                    <td>
                                        <a href="{% url 'wmdadict:dictionary_detail' row.dict_field.pk %}">{{ row.dict_field.label }}</a><br />
                                        {% if row.dict_field.description_short %}
                                            ({{ row.dict_field.description_short }})
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% for efield in row.dict_field.emdisfield_set.all %}
                                            <a href="{% url 'wmdadict:emdis_detail' efield.pk %}">{{ efield.field_code }}</a><br />
                                        {% endfor %}
                                    </td>
                                    <td>
                                        {% for bfield in row.dict_field.bmdwfield_set.all %}
                                            <a href="{% url 'wmdadict:bmdw_detail' bfield.pk  %}">{{ bfield.field_identifier }}</a><br />
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>No form fields are available.</p>
            {% endif %}
{% endblock %}

wmdadict/templates/wmdadict/index.html
<p>Test index page.</p>