wmdadict/urls.py
from django.conf.urls import url

from . import views

app_name = 'wmdadict'
urlpatterns = [
    # # /
    # url(r'^$', views.index, name='index'),
    # /dict/
    url(r'^dict/$', views.dictionary_list, name='dictionary_list'),
    # /dict/5/
    url(r'^dict/(?P<field_id>[0-9]+)/$', views.dictionary_detail, name='dictionary_detail'),
    # /emdis/fields/
    url(r'^emdis/fields/$', views.emdis_list, name='emdis_list'),
    # /emdis/field/5/
    url(r'^emdis/field/(?P<field_id>[0-9]+)/$', views.emdis_detail, name='emdis_detail'),
    # /emdis/messages/
    url(r'^emdis/messages/$', views.emdis_msg_list, name='emdis_msg_list'),
    # /emdis/message/5/
    url(r'^emdis/message/(?P<msg_id>[0-9]+)/$', views.emdis_msg_detail, name='emdis_msg_detail'),
    # /bmdw/
    url(r'^bmdw/$', views.bmdw_list, name='bmdw_list'),
    # /bmdw/5/
    url(r'^bmdw/(?P<field_id>[0-9]+)/$', views.bmdw_detail, name='bmdw_detail'),
    # /form/
    url(r'^form/$', views.form_list, name='form_list'),
    # /form/5/
    url(r'^form/(?P<field_id>[0-9]+)/$', views.form_detail, name='form_detail'),
]

wmdasite/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView

from wmdadict.admin import wmda_admin_site


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'', include('wmdadict.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^admin/', wmda_admin_site.urls),
]

if settings.LOCAL_DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

wmdasite/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">
          <img alt="WMDA logo" width="80px" src="{% static 'img/logo_blue.png' %}">
      </a>
    </div>
    <div class="collapse navbar-collapse" id="main-menu">
      <ul class="nav navbar-nav">
        <li{% if '/dict/' in request.path %} class="active"{% endif %}>
          <a href="{% url 'wmdadict:dictionary_list' %}">Main Dictionary</a>
        </li>
        <li {% if '/emdis/' in request.path %}
            class="active dropdown"
        {% else %}
            class="dropdown"
        {% endif %}>
          <a href="{% url 'wmdadict:emdis_list' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">EMDIS <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'wmdadict:emdis_list' %}">EMDIS Fields</a></li>
            <li><a href="{% url 'wmdadict:emdis_msg_list' %}">EMDIS Messages</a></li>
          </ul>
        </li>
        <li {% if '/bmdw/' in request.path %} class="active"{% endif %}>
          <a href="{% url 'wmdadict:bmdw_list' %}">BMDW</a>
        </li>
        <li {% if '/form/' in request.path %} class="active"{% endif %}>
            <a href="{% url 'wmdadict:form_list' %}">WMDA Forms</a>
        </li>
      </ul>
    </div>
  </div>
</nav>